name: Testy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Zainstaluj zależności
        run: pip install -r requirements-common.txt -r requirements-dev.txt

      - name: Uruchom pytest
        run: pytest -v
